-- Group profile schema additions
alter table public.groups
  add column if not exists profile_cover_url text,
  add column if not exists profile_description text;

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  name text not null,
  role text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.group_members enable row level security;

-- Admin can manage member cards
create policy "Admins can manage group members"
  on public.group_members
  for all
  to authenticated
  using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- Users can read member cards
create policy "Users can read group members"
  on public.group_members
  for select
  to authenticated
  using (true);
