-- Transfer feature schema
alter table public.groups
  add column if not exists transfer_enabled boolean default false;
create table if not exists public.transfer_rules (
  id bigint generated by default as identity primary key,
  target_group_id bigint not null references public.groups(id),
  source_group_id bigint not null references public.groups(id),
  mode text not null check (mode in ('FULL', 'CAP')),
  cap_points integer,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.transfer_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  user_id uuid not null,
  source_group_id bigint not null references public.groups(id),
  created_at timestamptz not null default now(),
  used_at timestamptz,
  used_by_user_id uuid,
  used_target_group_id bigint references public.groups(id)
);

create table if not exists public.transfer_logs (
  id bigint generated by default as identity primary key,
  from_group_id bigint not null references public.groups(id),
  to_group_id bigint not null references public.groups(id),
  from_user_id uuid not null,
  to_user_id uuid not null,
  points_transferred integer not null,
  created_at timestamptz not null default now()
);

-- RLS
alter table public.transfer_rules enable row level security;
alter table public.transfer_codes enable row level security;
alter table public.transfer_logs enable row level security;

-- transfer_rules: admin only (adjust to your admin role)
create policy "Admins can manage transfer rules"
  on public.transfer_rules
  for all
  to authenticated
  using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- transfer_codes: users can create and view their own codes
create policy "Users can manage own transfer codes"
  on public.transfer_codes
  for all
  to authenticated
  using (auth.uid() = user_id or auth.uid() = used_by_user_id or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
  with check (auth.uid() = user_id or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- transfer_logs: users can read own logs
create policy "Users can read own transfer logs"
  on public.transfer_logs
  for select
  to authenticated
  using (auth.uid() = from_user_id or auth.uid() = to_user_id or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

create policy "Admins can write transfer logs"
  on public.transfer_logs
  for insert
  to authenticated
  with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
