-- Enable RLS (Row Level Security) is recommended for production, 
-- but for this prototype we will allow public access or authenticated access depending on needs.
-- For simplicity in this phase, we assume the API is secured by the Anon Key and application logic.

-- 1. Groups Table
CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    theme_color TEXT DEFAULT '#2563EB',
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Gifts Table
CREATE TABLE IF NOT EXISTS gifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL DEFAULT 1, -- References groups(id)
    name TEXT NOT NULL,
    points_required INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    stock INTEGER,
    image TEXT,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Rank Configs Table
CREATE TABLE IF NOT EXISTS rank_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL DEFAULT 1, -- References groups(id)
    name TEXT NOT NULL,
    min_points INTEGER NOT NULL DEFAULT 0,
    color TEXT DEFAULT '#F59E0B',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Card Designs Table
CREATE TABLE IF NOT EXISTS card_designs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL DEFAULT 1, -- References groups(id)
    name TEXT NOT NULL,
    image_url TEXT,
    theme_color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Point History Table (Transaction Log)
CREATE TABLE IF NOT EXISTS point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    group_id BIGINT NOT NULL DEFAULT 1,
    points INTEGER NOT NULL,
    type TEXT NOT NULL, -- 'GRANT', 'USE_TICKET', 'GRANT_DESIGN'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    metadata JSONB -- Stores ticketId, designId details
);

-- 6. User Designs Table (Ownership Log)
CREATE TABLE IF NOT EXISTS user_designs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    group_id BIGINT NOT NULL DEFAULT 1,
    design_id BIGINT NOT NULL,
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, design_id) -- Prevent duplicate ownership of same design
);

-- 7. User Tickets Table (Ownership Log - Optional, can be derived from history but good for fast lookup)
CREATE TABLE IF NOT EXISTS user_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    group_id BIGINT NOT NULL DEFAULT 1,
    gift_id BIGINT NOT NULL,
    gift_name TEXT,
    status TEXT DEFAULT 'UNUSED', -- 'UNUSED', 'USED'
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE
);


-- Storage Bucket Setup for Card Designs
INSERT INTO storage.buckets (id, name, public) 
VALUES ('card-designs', 'card-designs', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies (Allow public read, authenticated upload)
-- Note: You might need to enable RLS on storage.objects first in Supabase Dashboard
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'card-designs' );

CREATE POLICY "Authenticated Upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'card-designs' AND auth.role() = 'authenticated' );
