-- 1. User Memberships Table (for persistence)
create table if not exists public.user_memberships (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  group_id bigint references public.groups not null,
  points integer default 0,
  total_points integer default 0,
  current_rank text default 'REGULAR',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, group_id)
);

-- 2. Enable RLS
alter table public.user_memberships enable row level security;

-- 3. Policies
create policy "Users can view their own memberships"
  on public.user_memberships for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own memberships"
  on public.user_memberships for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own memberships"
  on public.user_memberships for update
  using ( auth.uid() = user_id );

-- 4. Grant permissions
grant all on public.user_memberships to authenticated;
grant all on public.user_memberships to service_role;




