-- Create user_tickets table for persistence
create table if not exists public.user_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  group_id bigint references public.groups not null,
  gift_id bigint references public.gifts not null,
  gift_name text not null,
  status text default 'UNUSED', -- 'UNUSED', 'USED'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  used_at timestamp with time zone
);

-- Enable RLS
alter table public.user_tickets enable row level security;

-- Policies
create policy "Users can view their own tickets"
  on public.user_tickets for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own tickets"
  on public.user_tickets for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own tickets"
  on public.user_tickets for update
  using ( auth.uid() = user_id );

-- Grant permissions
grant all on public.user_tickets to authenticated;
grant all on public.user_tickets to service_role;




