-- 1. Card Designs Table (Metadata)
create table if not exists public.card_designs (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups not null,
  name text not null,
  image_url text not null,
  theme_color text default '#ffffff',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. User Designs Table (Ownership)
create table if not exists public.user_designs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  group_id bigint references public.groups not null,
  design_id bigint references public.card_designs not null,
  acquired_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, group_id, design_id) -- Prevent duplicate ownership
);

-- 3. Enable RLS
alter table public.card_designs enable row level security;
alter table public.user_designs enable row level security;

-- 4. Policies

-- Card Designs: Everyone can read, Authenticated (Admin) can insert/update/delete
drop policy if exists "Anyone can view card designs" on public.card_designs;
create policy "Anyone can view card designs"
  on public.card_designs for select
  using ( true );

drop policy if exists "Authenticated users can insert card designs" on public.card_designs;
create policy "Authenticated users can insert card designs"
  on public.card_designs for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can update card designs" on public.card_designs;
create policy "Authenticated users can update card designs"
  on public.card_designs for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can delete card designs" on public.card_designs;
create policy "Authenticated users can delete card designs"
  on public.card_designs for delete
  using ( auth.role() = 'authenticated' );

-- User Designs: Users can view their own, Authenticated (Admin) can insert/update for users
drop policy if exists "Users can view their own designs" on public.user_designs;
create policy "Users can view their own designs"
  on public.user_designs for select
  using ( auth.uid() = user_id );

-- Allow authenticated users (Admins) to insert for ANY user
drop policy if exists "Authenticated users can insert user designs" on public.user_designs;
create policy "Authenticated users can insert user designs"
  on public.user_designs for insert
  with check ( auth.role() = 'authenticated' );

-- Allow authenticated users (Admins) to update for ANY user (Required for Upsert/Sync)
drop policy if exists "Authenticated users can update user designs" on public.user_designs;
create policy "Authenticated users can update user designs"
  on public.user_designs for update
  using ( auth.role() = 'authenticated' );

-- Grant permissions
grant all on public.card_designs to authenticated;
grant all on public.card_designs to service_role;
grant all on public.card_designs to anon; -- allow public read of designs (images)

grant all on public.user_designs to authenticated;
grant all on public.user_designs to service_role;
