-- Create point_history table
CREATE TABLE IF NOT EXISTS point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    group_id INTEGER NOT NULL DEFAULT 1,
    points INTEGER NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    metadata JSONB
);

-- Create user_designs table
CREATE TABLE IF NOT EXISTS user_designs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    group_id INTEGER NOT NULL DEFAULT 1,
    design_id INTEGER NOT NULL,
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, design_id)
);

-- Create Storage Bucket for card designs
INSERT INTO storage.buckets (id, name, public) 
VALUES ('card-designs', 'card-designs', true)
ON CONFLICT (id) DO NOTHING;

-- Set up Storage Policies (Allow public read, authenticated upload)
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'card-designs' );

CREATE POLICY "Authenticated Upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'card-designs' AND auth.role() = 'authenticated' );
